// 抛出错误
export default function handleError(msg: string){
  throw new Error(msg)
}